version: "2.1"

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: production
    ports:
      - 80:3000
    networks:
      - my_network

  mongodb:
    image: mongo
    networks:
      - my_network

networks: 
  my_network:
    driver: bridge